# spotify oauth token
spotify_token = "BQA4CyDea26l57cE6Imp_Sbgq1agzyTQpynnzSa6yGTTjHZaJXW1m-JT5XYUplVpM5BdG9KmRoTz4AuUd1Ab7bFrVXIDtC2kr17zMNTtu-8daeb8QvzDg1gbnHZpBZG-i6m2bBnbm-UbbE-OaawiCxQtQbp2mHJlbqPNebxwBDnN9xH0kOjg-hyDfUtXAVJ2BLqPuj8SDABCGXTQ92_ycdM"

# your local login on your computer
username = "lukelevasseur"
